# https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#check-organization-membership-for-a-user

# Use by
# Community Portal
# File: pkg/github/github.go
# Function: IsOrganizationMember
# Scope: *

###
# Headers
# @prompt token Enter your github token:

# Path parameters
# @prompt org Enter the organization name:
# @prompt username Enter the username of the user whose membership you want to check:

GET https://api.github.com/orgs/{{org}}/members/{{username}}
Accept: application/vnd.github+json
Authorization: Bearer {{token}}
X-GitHub-Api-Version: 2022-11-28
X-Github-Next-Global-ID: 1
