# https://docs.github.com/en/graphql/reference/queries#enterprise

# Use by
# Community Portal
# File: pkg/github/github.go
# Function: GetOrganizationsWithinEnterprise
# Scope: Enterprise Organizations

###
# Headers
# @prompt token Enter your github token:

# Variables
# @prompt enterprise Enter the github enterprise slug:
# @prompt cursor Enter the pagination cursor (or leave empty for first page):

POST https://api.github.com/graphql
X-REQUEST-TYPE: GraphQL
Authorization: Bearer {{token}}
X-Github-Next-Global-ID: 1

query getEntepriseOrganizations($enterprise: String!, $cursor: String) {
  enterprise(slug: $enterprise) {
    id
    databaseId
    organizations(first: 100, after: $cursor) {
      nodes {
        login
        databaseId
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}

{
  "enterprise": "{{enterprise}}",
  "cursor": null
}