# https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#get-a-team-by-name

# Use by
# Community Portal
# File: pkg/github/github.go
# Function: GetTeam
# Scope: Enterprise Organizations

###
# Headers
# @prompt token Enter your github token:

# Path parameters
# @prompt org Enter the organization name:
# @prompt team_slug Enter the team slug:

GET https://api.github.com/orgs/{{org}}/teams/{{team_slug}}
Accept: application/vnd.github+json
Authorization: Bearer {{token}}
X-GitHub-Api-Version: 2022-11-28
X-Github-Next-Global-ID: 1
