# https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories

# Use by
# Community Portal
# File: pkg/github/github.go
# Function: GetRepositoriesFromOrganization
# Scope: *

###
# Headers
# @prompt token Enter your github token:

# Path parameters
# @prompt org Enter the organization name:

# Query parameters
# @prompt type (all, public, private, forks, sources, member, internal) Enter the type of repositories to list: all
# @prompt sort (created, updated, pushed, full_name) Enter the field to sort results by: full_name
# @prompt direction (asc, desc) Enter the direction of the sort: asc
# @prompt per_page Enter the number of results per page (max 100): 30
# @prompt page Enter the page number of the results to fetch: 1

GET https://api.github.com/orgs/{{org}}/repos
    ?type={{type}}
    &sort={{sort}}
    &direction={{direction}}
    &per_page={{per_page}}
    &page={{page}}
Accept: application/vnd.github+json
Authorization: Bearer {{token}}
X-GitHub-Api-Version: 2022-11-28
X-Github-Next-Global-ID: 1
