# https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#update-a-repository

# Use by
# Community Portal
# File: pkg/github/github.go
# Function: SetProjectVisibility
# Scope: *

###
# Headers
# @prompt token Enter your github token:

# Path parameters
# @prompt owner Enter the repository owner:
# @prompt repo Enter the repository name:

# Body parameters
# @prompt visibility (public, private, internal) Enter the visibility of the repository: private

PATCH https://api.github.com/repos/{{owner}}/{{repo}}
Accept: application/vnd.github+json
Authorization: Bearer {{token}}
X-GitHub-Api-Version: 2022-11-28
X-Github-Next-Global-ID: 1

{
  "visibility": "{{visibility}}"
}
