name: Deploy Github Management Workflow

on:
  workflow_dispatch:
    inputs:
      selected_environment:
        type: choice
        description: SELECT ENVIRONMENT
        required: true
        default: dev
        options: 
        - prod
        - uat
        - dev

env:
  PROJECT_NAME: ${{github.event.inputs.selected_environment}}-gh-mgmt-app

jobs:
  build-and-deploy-in-acr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/goapp
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.ACR_REGISTRY }}/${{ env.PROJECT_NAME }}:${{ github.sha }} -t ${{ secrets.ACR_REGISTRY }}/${{ env.PROJECT_NAME }}:latest
          docker push ${{ secrets.ACR_REGISTRY }}/${{ env.PROJECT_NAME }}

  deploy-server-and-database:
    if: ${{ needs.build-and-deploy-in-acr.result == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      database_name: ${{ steps.create_database.outputs.database_name }}
    steps:

    - uses: actions/checkout@v2

    - id: string
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{github.event.inputs.selected_environment}}

    - name: Create database name
      id: create_database
      run: |
        echo "database_name=${{steps.string.outputs.uppercase}}GhManagementDb" >> $GITHUB_OUTPUT

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy SQL Server & Database
      uses: azure/arm-deploy@v1
      with:
        deploymentName: Deploy SQL Server & Database
        subscriptionId: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['subscriptionId'] }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./.bicep/sql/main.bicep
        parameters: serverName=${{ secrets.SERVER_NAME }} administratorLogin=${{ secrets.SERVER_USERNAME }} administratorLoginPassword=${{ secrets.SERVER_PASSWORD }} databaseName=${{ steps.create_database.outputs.database_name }}
        failOnStdErr: false
        scope: resourcegroup

    - uses: azure/sql-action@v1.3
      with:
        connection-string: Server=${{ secrets.SERVER_NAME }}.database.windows.net;Initial Catalog=${{ steps.create_database.outputs.database_name }};Persist Security Info=False;User ID=${{ secrets.SERVER_USERNAME }};Password=${{ secrets.SERVER_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
        project-file: 'src/sqldb/sqldb.sqlproj'

  deploy-appserviceplan-and-webapp:
    if: ${{ needs.jobsdeploy-server-and-database.result == 'success' }}
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup Azure Credentials
      run: |
        cat > az_cred.json <<EOL
          ${{ secrets.AZURE_CREDENTIALS }}
        EOL

        TENANT_ID=`jq -r '.tenantId' az_cred.json`
        CLIENT_ID=`jq -r '.clientId' az_cred.json`
        CLIENT_SECRET=`jq -r '.clientSecret' az_cred.json`

        echo "::add-mask::$TENANT_ID"
        echo "::add-mask::$CLIENT_ID"
        echo "::add-mask::$CLIENT_SECRET"

        echo "TENANT_ID=$TENANT_ID" >> $GITHUB_ENV
        echo "CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
        echo "CLIENT_SECRET=$CLIENT_SECRET" >> $GITHUB_ENV

    - name: Setup Dev Github Credentials
      run: |
        case ${{ github.event.inputs.selected_environment }} in
          "dev")
        cat > gh_cred.json <<EOL
          ${{ secrets.GH_CREDENTIALS_DEV }}
        EOL
            ;;
          "uat")
        cat > gh_cred.json <<EOL
          ${{ secrets.GH_CREDENTIALS_UAT }}
        EOL
            ;;
        esac

        CLIENT_ID=`jq -r '.clientId' gh_cred.json`
        CLIENT_SECRET=`jq -r '.clientSecret' gh_cred.json`
        TOKEN=`jq -r '.token' gh_cred.json`

        echo "::add-mask::$CLIENT_ID"
        echo "::add-mask::$CLIENT_SECRET"
        echo "::add-mask::$TOKEN"

        echo "GH_CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
        echo "GH_CLIENT_SECRET=$CLIENT_SECRET" >> $GITHUB_ENV
        echo "GH_TOKEN=$TOKEN" >> $GITHUB_ENV

    - name: SUBSTITUTE VARIABLES
      uses: microsoft/variable-substitution@v1 
      with:
        files: ./.bicep/webapp/${{ github.event.inputs.selected_environment }}-parameters.json
      env:
        parameters.sqlServerName.value : ${{ secrets.SERVER_NAME }}
        parameters.projectName.value : ${{ env.PROJECT_NAME }}
        parameters.containerServer.value : ${{ secrets.ACR_REGISTRY }}
        parameters.appServiceSettings.value.DOCKER_REGISTRY_SERVER_URL : https://${{ secrets.ACR_REGISTRY }}
        parameters.appServiceSettings.value.DOCKER_REGISTRY_SERVER_USERNAME : ${{ secrets.ACR_USERNAME }} 
        parameters.appServiceSettings.value.DOCKER_REGISTRY_SERVER_PASSWORD : ${{ secrets.ACR_PASSWORD }} 
        parameters.appServiceSettings.value.TENANT_ID : ${{ secrets.AD_TENANT_ID_DEV }}
        parameters.appServiceSettings.value.CLIENT_ID : ${{ secrets.AD_CLIENT_ID_DEV }}
        parameters.appServiceSettings.value.CLIENT_SECRET : ${{ secrets.AD_CLIENT_SECRET_DEV }}
        parameters.appServiceSettings.value.HOME_URL : 'https://${{ env.PROJECT_NAME }}.azurewebsites.net'
        parameters.appServiceSettings.value.EMAIL_ENDPOINT : ${{ secrets.EMAIL_ENDPOINT }}
        parameters.appServiceSettings.value.GH_CLIENT_ID : ${{ env.GH_CLIENT_ID }}
        parameters.appServiceSettings.value.GH_CLIENT_SECRET : ${{ env.GH_CLIENT_SECRET }}
        parameters.appServiceSettings.value.GH_TOKEN : ${{ env.GH_TOKEN }}
        parameters.appServiceSettings.value.GHMGMTDB_CONNECTION_STRING : Server=tcp:${{ secrets.SERVER_NAME }}.database.windows.net,1433;Initial Catalog=${{ needs.jobs.deploy-server-and-database.outputs.database_name }};Persist Security Info=False;User ID=${{ secrets.SERVER_USERNAME }};Password=${{ secrets.SERVER_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy App Service Plan and Web App
      uses: azure/arm-deploy@v1
      with:
        deploymentName: Deploy App Service Plan & Web App
        subscriptionId: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['subscriptionId'] }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./.bicep/webapp/main.bicep
        parameters: ./.bicep/webapp/${{ github.event.inputs.selected_environment }}-parameters.json
        failOnStdErr: false
        scope: resourcegroup