name: Deploy Logic App Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      selected_environment:
        type: choice
        description: SELECT ENVIRONMENT
        require: true
        default: TEST
        options: 
        - PROD
        - UAT
        - TEST
jobs:
  build-gh-logic-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configuration for PRODUCTION environment
        if: ${{ github.event.inputs.selected_environment == 'PROD' }}
        run: |
          echo "GH_DOMAIN=${{ secrets.GH_DOMAIN_PROD }}" >> $GITHUB_ENV
          echo "ACTIVE_ENV=PROD" >> $GITHUB_ENV

      - name: Configuration for UAT environment
        if: ${{ github.event.inputs.selected_environment == 'UAT' }}
        run: |
          echo "GH_DOMAIN=${{ secrets.GH_DOMAIN_UAT }}" >> $GITHUB_ENV
          echo "ACTIVE_ENV=UAT" >> $GITHUB_ENV

      - name: Configuration for TEST environment
        if: ${{ github.event.inputs.selected_environment == 'TEST' }}
        run: |
          echo "GH_DOMAIN=${{ secrets.GH_DOMAIN_TEST }}" >> $GITHUB_ENV
          echo "ACTIVE_ENV=TEST" >> $GITHUB_ENV
        
      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Prepare environment variables
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: | 
          # Parse Azure secret into Terraform variables
          $servicePrincipal = ($env:AZURE_CREDENTIALS | ConvertFrom-Json)
          echo "AZURE_PRINCIPAL_ID=$servicePrincipal.clientId" >> $GITHUB_ENV
          echo "AZURE_TENANT_ID=$servicePrincipal.tenantId" >> $GITHUB_ENV
        shell: pwsh

      - name: Deploy Bicep File
        uses: azure/arm-deploy@v1
        id: deploy_main_bicep
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./.bicep/main.bicep
          parameters: env=${{ env.ACTIVE_ENV }} LAManageIdentityName=${{ secrets.LOGIC_APP_MANAGE_IDENTITY}}
          failOnStdErr: false

      - name: Setup Workflow Parameters
        uses: microsoft/variable-substitution@v1 
        with:
          files: './.bicep/workflows/parameters.json'
        env:
          GHMgmDomain.value: ${{ env.GH_DOMAIN }}
          
      - name: Upload Logic App Workflows
        uses: azure/CLI@v1
        with:
          azcliversion: 2.44.1
          inlineScript: |
            echo "AZURE PRINCIPAL ID : ${{env.AZURE_PRINCIPAL_ID}}"
            echo "AZURE TENANT ID : ${{env.AZURE_TENANT_ID}}"
            chmod +x ./.bicep/upload_workflows.sh
            ./.bicep/upload_workflows.sh ${{steps.deploy_main_bicep.outputs.accountName}} ${{steps.deploy_main_bicep.outputs.destination}}

      - name: Deploy Connection Bicep File
        uses: azure/arm-deploy@v1
        id: deploy_connection_bicep
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./.bicep/connection.bicep
          parameters: env=${{ env.ACTIVE_ENV }} storageAccountName=${{steps.deploy_main_bicep.outputs.accountName}} principalId=${{env.AZURE_PRINCIPAL_ID}} tenantId=${{env.AZURE_TENANT_ID}}
          failOnStdErr: false

      - name: Deploy connection to storage file system
        shell: pwsh
        run: |
          ./.bicep/deploy_connection.ps1 `
            New-WorkflowConnection `
              -ResourceGroup ${{secrets.AZURE_RG}} `
              -StorageAccount ${{steps.deploy_main_bicep.outputs.accountName}} `
              -Api ${{steps.deploy_connection_bicep.outputs.api}} `
              -Id ${{steps.deploy_connection_bicep.outputs.id}} `
              -RuntimeUrl ${{steps.deploy_connection_bicep.outputs.connectionRuntimeUrl}}