name: Deploy Logic App Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      selected_environment:
        type: choice
        description: SELECT ENVIRONMENT
        required: true
        default: test
        options: 
        - test
        - uat
        - prod

env:
  PROJECT_NAME: ava-gh-mgmt
  ACTIVE_ENV: ${{github.event.inputs.selected_environment}}

jobs:
  build-gh-logic-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configuration for PRODUCTION environment
        if: ${{ github.event.inputs.selected_environment == 'PROD' }}
        run: |
          case ${{ github.event.inputs.selected_environment }} in
            "prod")
                echo "GH_DOMAIN=${{secrets.CUSTOM_DOMAIN_PROD}}}" >> $GITHUB_ENV
                echo "ACTIVE_ENV=prod" >> $GITHUB_ENV
              ;;
            "test" | "uat")
                echo "GH_DOMAIN=https://${{ env.PROJECT_NAME }}-${{env.ACTIVE_ENV}}.azurewebsites.net" >> $GITHUB_ENV
                echo "ACTIVE_ENV=test" >> $GITHUB_ENV
              ;;
          esac
        
      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep File
        uses: azure/arm-deploy@v1
        id: deploy_main_bicep
        with:
          subscriptionId: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['subscriptionId'] }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./.bicep/logicapps/main.bicep
          parameters: env=${{ env.ACTIVE_ENV }} LAManageIdentityName=${{ secrets.LOGIC_APP_MANAGE_IDENTITY }}
          failOnStdErr: false
          scope: resourcegroup