name: Deploy IAC Workflow

on:
  workflow_dispatch:

jobs:
  deploy-server-and-database:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az keyvault secret show --name "tencommunityportal" --vault-name "ITS-AV-EmTech" --query "value"