name: Deploy IAC Workflow
run-name: Deploy IAC Workflow [${{inputs.selected_environment}}]

on:
  workflow_dispatch:
    inputs:
      selected_environment:
        type: choice
        description: SELECT ENVIRONMENT
        required: true
        default: test
        options: 
        - prod
        - uat
        - test
      disable_data_loss:
        type: boolean
        description: Block on possible data loss
        required: true
        default: true
      db_infra:
        type: boolean
        description: Run deployment of SQL Server resource
        required: true
        default: true
      db_project:
        type: boolean
        description: Run build and publish the SQL Project
        required: true
        default: true
      app_infra:
        type: boolean
        description: Run deployment of AppServicePlan and AppService
        required: true
        default: true
      frontdoor:
        type: boolean
        description: Run deployment of frontdoor
        required: true
        default: false
      frontdoor_customdomain:
        type: string
        description: Add custom domain in frontdoor frontend endpoint
        default: ''

env:
  PROJECT_NAME: ava-gh-mgmt
  ACTIVE_ENV: ${{github.event.inputs.selected_environment}}

jobs:
  deploy-server-and-database:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Azure Credentials
      run: |
        echo ${{ fromJSON(secrets.AZURE_CREDENTIALS)['subscriptionId'] }}
        echo ${{ fromJSON(secrets.AZURE_CREDENTIALS)['clientId'] }}
        echo ${{ fromJSON(secrets.AZURE_CREDENTIALS)['clientSecret'] }}
        echo ${{ fromJSON(secrets.AZURE_CREDENTIALS)['tenantId'] }}