name: Deploy Logic App Workflows
run-name: Deploy Logic App Workflows [${{inputs.selected_environment}}]

on:
  workflow_dispatch:
    inputs:
      selected_environment:
        type: choice
        description: SELECT ENVIRONMENT
        required: true
        default: test
        options: 
        - test
        - uat
        - prod
      cleanup_organization:
        description: 'Set workflow status'
        required: true
        default: 'Disabled'
        type: choice
        options:
          - Disabled
          - Enabled
      expiring_invitation:
        description: 'Set workflow status'
        required: true
        default: 'Disabled'
        type: choice
        options:
          - Disabled
          - Enabled
      fillout_approval_request_approvers:
        description: 'Set workflow status'
        required: true
        default: 'Disabled'
        type: choice
        options:
          - Disabled
          - Enabled
      fillout_approvers:
        description: 'Set workflow status'
        required: true
        default: 'Disabled'
        type: choice
        options:
          - Disabled
          - Enabled
      fillout_items_approvers:
        description: 'Set workflow status'
        required: true
        default: 'Disabled'
        type: choice
        options:
          - Disabled
          - Enabled
      index_org_repos:
        description: 'Set workflow status'
        required: true
        default: 'Disabled'
        type: choice
        options:
          - Disabled
          - Enabled
      innersource_check_outside_collaborators:
        description: 'Set workflow status'
        required: true
        default: 'Disabled'
        type: choice
        options:
          - Disabled
          - Enabled
      migrate_oss_sponsors:
        description: 'Set workflow status'
        required: true
        default: 'Disabled'
        type: choice
        options:
          - Disabled
          - Enabled
      opensource_check_outside_collaboratros:
        description: 'Set workflow status'
        required: true
        default: 'Disabled'
        type: choice
        options:
          - Disabled
          - Enabled
      recurring_approval:
        description: 'Set workflow status'
        required: true
        default: 'Disabled'
        type: choice
        options:
          - Disabled
          - Enabled
      repo_owner_scan:
        description: 'Set workflow status'
        required: true
        default: 'Disabled'
        type: choice
        options:
          - Disabled
          - Enabled

env:
  PROJECT_NAME: ava-gh-mgmt
  APPROVAL_SYSTEM_NAME: ava-approval-system
  ACTIVE_ENV: ${{github.event.inputs.selected_environment}}

jobs:
  build-gh-logic-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set GH_Domain and ACTIVE_ENV
        run: |
          case ${{ github.event.inputs.selected_environment }} in
            "prod")
                echo "GH_DOMAIN=${{secrets.CUSTOM_DOMAIN_PROD}}" >> $GITHUB_ENV
                echo "APPROVAL_SYSTEM_DOMAIN=${{secrets.CUSTOM_APPROVAL_SYSTEM_DOMAIN_PROD}}" >> $GITHUB_ENV
                echo "ACTIVE_ENV=prod" >> $GITHUB_ENV
                echo "LA_MANAGE_IDENTITY_NAME=${{secrets.LOGIC_APP_MANAGE_IDENTITY_PROD}}" >> $GITHUB_ENV
              ;;
            "test" | "uat")
                echo "GH_DOMAIN=https://${{ env.PROJECT_NAME }}-${{env.ACTIVE_ENV}}.azurewebsites.net" >> $GITHUB_ENV
                echo "APPROVAL_SYSTEM_DOMAIN=https://${{ env.APPROVAL_SYSTEM_NAME }}-${{env.ACTIVE_ENV}}.azurewebsites.net" >> $GITHUB_ENV
                echo "ACTIVE_ENV=${{env.ACTIVE_ENV}}" >> $GITHUB_ENV
                echo "LA_MANAGE_IDENTITY_NAME=${{secrets.LOGIC_APP_MANAGE_IDENTITY}}" >> $GITHUB_ENV
              ;;
          esac
        
      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy Bicep File
        uses: azure/arm-deploy@v1
        id: deploy_main_bicep
        with:
          subscriptionId: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['subscriptionId'] }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./.bicep/logicapps/deployGhMgmtLogicApp.bicep
          parameters: env=${{ env.ACTIVE_ENV }} laManageIdentityName=${{ env.LA_MANAGE_IDENTITY_NAME }}
          failOnStdErr: false
          scope: resourcegroup

      - name: Setup Workflow Parameters
        uses: microsoft/variable-substitution@v1 
        with:
          files: ./.bicep/logicapps/workflows/parameters.json
        env:
          GHMgmDomain.value: ${{ env.GH_DOMAIN }}
          ManagedIdentityName.value: ${{ env.LA_MANAGE_IDENTITY_NAME }}
          ApprovalSystemDomain.value: ${{ env.APPROVAL_SYSTEM_DOMAIN }}
          
      - name: Upload Logic App Workflows
        uses: azure/CLI@v1
        with:
          azcliversion: 2.44.1
          inlineScript: |
            chmod +x ./.bicep/logicapps/upload_workflows.sh
            ./.bicep/logicapps/upload_workflows.sh ${{steps.deploy_main_bicep.outputs.accountName}} ${{steps.deploy_main_bicep.outputs.destination}} ./.bicep/logicapps/workflows

      - name: Setup Workflow Parameters
        uses: microsoft/variable-substitution@v1 
        with:
          files: ./.bicep/logicapps/parameters.json
        env:
          parameters.env.value: ${{ env.ACTIVE_ENV }}
          parameters.appSettings.value.Workflows.CleanupOrganization.FlowState: ${{ github.event.inputs.cleanup_organization }}
          parameters.appSettings.value.Workflows.ExpiringInvitation.FlowState: ${{ github.event.inputs.expiring_invitation }}
          parameters.appSettings.value.Workflows.FillOutApprovalRequestApprovers.FlowState: ${{ github.event.inputs.fillout_approval_request_approvers }}
          parameters.appSettings.value.Workflows.FillOutApprovers.FlowState: ${{ github.event.inputs.fillout_approvers }}
          parameters.appSettings.value.Workflows.FillOutItemsApprovers.FlowState: ${{ github.event.inputs.fillout_items_approvers }}
          parameters.appSettings.value.Workflows.IndexOrgRepos.FlowState: ${{ github.event.inputs.index_org_repos }}
          parameters.appSettings.value.Workflows.InnersourceCheckOutsideCollaborators.FlowState: ${{ github.event.inputs.innersource_check_outside_collaborators }}
          parameters.appSettings.value.Workflows.OpensourceCheckOutsideCollaborators.FlowState: ${{ github.event.inputs.opensource_check_outside_collaboratros }}
          parameters.appSettings.value.Workflows.MigrateOssSponsors.FlowState: ${{ github.event.inputs.migrate_oss_sponsors }}
          parameters.appSettings.value.Workflows.RecurringApproval.FlowState: ${{ github.event.inputs.recurring_approval }}
          parameters.appSettings.value.Workflows.RepoOwnerScan.FlowState: ${{ github.event.inputs.repo_owner_scan }}

      - name: Set Workflows Appsettings
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['subscriptionId'] }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./.bicep/logicapps/deploySetWorkflowsAppsettings.bicep
          parameters:  ./.bicep/logicapps/parameters.json
          failOnStdErr: false
          scope: resourcegroup
        

      - name: Deploy Connection Bicep File
        uses: azure/arm-deploy@v1
        id: deploy_connection_bicep
        with:
          subscriptionId: ${{ fromJSON(secrets.AZURE_CREDENTIALS)['subscriptionId'] }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./.bicep/logicapps/connection.bicep
          parameters: env=${{ env.ACTIVE_ENV }} storageAccountName=${{steps.deploy_main_bicep.outputs.accountName}} logicAppName=${{steps.deploy_main_bicep.outputs.logicAppName}} laManageIdentityName=${{ env.LA_MANAGE_IDENTITY_NAME }}
          failOnStdErr: false
          scope: resourcegroup

      - name: Deploy connection to storage file system
        uses: azure/powershell@v1
        with:
          inlineScript: |
            . ./.bicep/logicapps/deploy_connection.ps1
            New-WorkflowConnection `
              -ResourceGroup ${{secrets.AZURE_RG}} `
              -StorageAccount ${{steps.deploy_main_bicep.outputs.accountName}} `
              -Api ${{steps.deploy_connection_bicep.outputs.api}} `
              -Id ${{steps.deploy_connection_bicep.outputs.id}} `
              -RuntimeUrl ${{steps.deploy_connection_bicep.outputs.connectionRuntimeUrl}} `
              -FileShareName ${{steps.deploy_main_bicep.outputs.fileShare}}
          azPSVersion: "latest"