name: Test - Docker Container - GH-Management

on:
  push:
    branches:
      - test
    paths:
      - "src/goapp/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: src/goapp

jobs:
  build-goapp-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.ACR_REGISTRY }}/test-gh-mgmt-app:${{ github.sha }} -t ${{ secrets.ACR_REGISTRY }}/test-gh-mgmt-app:latest
          docker push ${{ secrets.ACR_REGISTRY }}/test-gh-mgmt-app

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file
      - name: Deploy Bicep File
        uses: azure/arm-deploy@v1
        id: deploy_bicep
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./.bicep/main.bicep
          parameters: env=test LAManageIdentityName=${{ secrets.LOGIC_APP_MANAGE_IDENTITY}}
          failOnStdErr: false

      - name: Setup workflow parameters
        uses: microsoft/variable-substitution@v1 
        with:
          files: './.bicep/workflows/parameters.json'
        env:
          CleaupOrganizationEndpoint.value: ${{ secrets.CLEANUP_ORGANIZATION_ENDPOINT }}
          InnersourceCheckOutsideCollaboratorsEndpoint.value: ${{ secrets.INNERSOURCE_CHECK_OUTSIDE_COLLABORATORS_ENDPOINT }}
          IndexOrgReposEndpoint.value: ${{ secrets.INDEX_ORG_REPOS_ENDPOINT }}
          OpensourceCheckOutsideCollaboratorsEndpoint.value: ${{ secrets.OPENSOURCE_CHECK_OUTSIDE_COLLABORATORS_ENDPOINT }}

      - name: Upload Logic App Workflows
        uses: azure/CLI@v1
        with:
          azcliversion: 2.44.1
          inlineScript: |
            chmod +x ./.bicep/upload_workflows.sh
            ./.bicep/upload_workflows.sh ${{steps.deploy_bicep.outputs.accountName}} ${{steps.deploy_bicep.outputs.destination}}